/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AIQuery = IDL.Record({
  'id' : IDL.Text,
  'result' : IDL.Text,
  'queryText' : IDL.Text,
});
export const DataSource = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'name' : IDL.Text,
});
export const BotConfig = IDL.Record({
  'id' : IDL.Text,
  'queries' : IDL.Vec(AIQuery),
  'dataSources' : IDL.Vec(DataSource),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addDataSource' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createBotConfig' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(AIQuery)],
      [],
      [],
    ),
  'getAllBotConfigs' : IDL.Func([], [IDL.Vec(BotConfig)], ['query']),
  'getAllDataSources' : IDL.Func([], [IDL.Vec(DataSource)], ['query']),
  'getBotConfig' : IDL.Func([IDL.Text], [BotConfig], ['query']),
  'getDataSource' : IDL.Func([IDL.Text], [DataSource], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AIQuery = IDL.Record({
    'id' : IDL.Text,
    'result' : IDL.Text,
    'queryText' : IDL.Text,
  });
  const DataSource = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'name' : IDL.Text,
  });
  const BotConfig = IDL.Record({
    'id' : IDL.Text,
    'queries' : IDL.Vec(AIQuery),
    'dataSources' : IDL.Vec(DataSource),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addDataSource' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createBotConfig' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(AIQuery)],
        [],
        [],
      ),
    'getAllBotConfigs' : IDL.Func([], [IDL.Vec(BotConfig)], ['query']),
    'getAllDataSources' : IDL.Func([], [IDL.Vec(DataSource)], ['query']),
    'getBotConfig' : IDL.Func([IDL.Text], [BotConfig], ['query']),
    'getDataSource' : IDL.Func([IDL.Text], [DataSource], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };